<?php /** @var Postdirekt_Autocomplete_Block_Adminhtml_System_Config_Custominformation $this */ ?>
<div class="postdirekt-autocomplete-custom-info">
    <header>
        <img src="<?php echo $this->escapeUrl($this->getLogoUrl()) ?>">
        <p class="info">
            <?php echo $this->escapeHtml($this->__('Version:')) ?>
            <?php echo $this->escapeHtml($this->getModuleVersion()) ?>
        </p>
    </header>
    <div class="container">
        <div class="row">
            <div class="col content">
                <p>
                    <?php echo $this->escapeHtml(
                        $this->__(
                            // @codingStandardsIgnoreLine
                            'The DATAFACTORY AUTOCOMPLETE from Deutsche Post Direkt offers effective support for address collection in online business. DATAFACTORY AUTOCOMPLETE is easily integrated into your ordering process and conveniently assists during address entry using postal data based on the original Deutsche Post postal routing data. Address entry during the ordering process is made faster and more convenient, while minimizing address input errors. Your customer receives up to 15 suggestions as soon as the first alphanumeric characters are entered in the input field. More than 1.2 million different address suggestions are available, including all street names relevant for delivery, more than 16,000 postcodes with destinations, 14,000 cities, and 75,000 districts.'
                        )
                    ); ?>
                </p>
                <p><strong><?php echo $this->escapeHtml($this->__('To get started:')) ?></strong><br>
                    <?php echo /** @noEscape */ $this->__(
                        // @codingStandardsIgnoreLine
                            'You need a valid Deutsche Post Direkt account. If you do not have an account yet or your account is not enabled for DATAFACTORY AUTOCOMPLETE, please use the <a href="%s" target="_blank">Deutsche Post Direkt</a> website to use our address solutions.',
                        $this->escapeHtml('https://www.postdirekt.de/autocomplete')
                    );?>
                </p>
            </div>
        </div>
    </div>
</div>
