<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php /** @var Postdirekt_Autocomplete_Block_AddressHandler $this */ ?>
<script type="text/javascript">
    var searchUrl = '<?php echo $this->getSearchEndpoint() ?>',
        respondUrl = '<?php echo $this->getSelectEndpoint() ?>',
        formId = 'form-validate',
        watchedFieldIds = {
            'street': 'street_1',
            'city': 'city',
            'postcode': 'zip'
        },
        addressAutocomplete = new AddressAutocomplete(formId, searchUrl, respondUrl, watchedFieldIds);

    console.log('Init AddressAutocomplete in postdirekt_autocomplete/handler_customer.phtml', 'Address object: ', addressAutocomplete);
</script>
