<?php
/**
 * See LICENSE.md for license details.
 */

/** @var Postdirekt_Autocomplete_Block_AddressHandler $this */
$token = $this->getToken();

if ($token) : ?>
<script type="text/javascript">
    postdirektAutocompleteLib.init(
        document.querySelector('#street_1'),
        document.querySelector('#city'),
        document.querySelector('#zip'),
        document.querySelector('#country'),
        'DE',
        '<?php echo $token; ?>'
    );
</script>
<?php endif; ?>
