<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php /** @var Postdirekt_Autocomplete_Block_AddressHandler $this */ ?>
<script type="text/javascript">
var searchUrl = '<?php echo $this->getSearchEndpoint() ?>',
    respondUrl = '<?php echo $this->getSelectEndpoint() ?>',

    addressAutocomplete = new AddressAutocomplete(
        'form-validate',
        searchUrl,
        respondUrl,
        {
            'street': 'street_1',
            'city': 'city',
            'postcode': 'zip'
        }
    );
</script>
